import Head from "next/head";
import { useEffect } from "react";
import styles from "@/styles/Home.module.css";
import CtaSection from "@/components/home/CtaSection";
import HeroSection from "@/components/home/HeroSection";
import AboutSection from "@/components/home/AboutSection";
import PartnerSection from "@/components/home/ParterSection";
import ProcessSection from "@/components/home/ProcessSection";
import ProjectSection from "@/components/home/ProjectSection";
import ServicesMobile from "@/components/home/ServicesMobile";
import ServicesSection from "@/components/home/ServicessSection";

export default function Home() {
  useEffect(() => {
    if ("scrollRestoration" in history) {
      history.scrollRestoration = "manual";
    }
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Head>
        <title>Corivis</title>
        <link rel="icon" href="/logo3.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.home_page}>
        {/* Top section of the page */}
        <section id="home" className={styles.hero_section}>
          <HeroSection />
        </section>
        {/* About corivis section */}
        <section id="about" className={styles.about_section}>
          <AboutSection />
        </section>
        {/* Service Sections */}
        <section id="services" className={styles.services_section}>
          <div className={styles.desktop}>
            <ServicesSection />
          </div>
          <div className={styles.mobile}>
            <ServicesMobile />
          </div>
        </section>
        {/* Project section of page */}
        <section id="projects" className={styles.project_section}>
          <ProjectSection />
        </section>
        {/* Delivery Approch Section */}
        <section className={styles.process_section}>
          <ProcessSection />
        </section>
        {/* Partnership section and testimonial or review section */}
        <section className={styles.partner_section}>
          <PartnerSection />
        </section>
        {/* Build something amazing section */}
        <section className={styles.cta_section}>
          <CtaSection />
        </section>
      </main>
    </>
  );
}